// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIVb1MGSMlkTgurtGwNmjrQ_QLj5U6ZPg',
    appId: '1:331289226813:web:340e5f10e4dfcf9da4c454',
    messagingSenderId: '331289226813',
    projectId: 'calender-app123',
    authDomain: 'calender-app123.firebaseapp.com',
    storageBucket: 'calender-app123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdbAWtwLULuAv3rYV1oah1kkj6YfiQJc',
    appId: '1:331289226813:android:375fbc38588e9e3ba4c454',
    messagingSenderId: '331289226813',
    projectId: 'calender-app123',
    storageBucket: 'calender-app123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-uwUMAk2rJyNFKBQNxNvLTsYg8imZOBg',
    appId: '1:331289226813:ios:682f5934a5dff713a4c454',
    messagingSenderId: '331289226813',
    projectId: 'calender-app123',
    storageBucket: 'calender-app123.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-uwUMAk2rJyNFKBQNxNvLTsYg8imZOBg',
    appId: '1:331289226813:ios:5535c8e297ac128fa4c454',
    messagingSenderId: '331289226813',
    projectId: 'calender-app123',
    storageBucket: 'calender-app123.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
