// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41xSuzrVta8sMiCiTUBQpxfJstLqnX1o',
    appId: '1:444197624164:web:6ba4541e645eeabfe98271',
    messagingSenderId: '444197624164',
    projectId: 'calender-booking-app-123',
    authDomain: 'calender-booking-app-123.firebaseapp.com',
    storageBucket: 'calender-booking-app-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7nS2OQefc7vaAaYh2pGFvH590sarfK_o',
    appId: '1:444197624164:android:68ca6394c88b9dcbe98271',
    messagingSenderId: '444197624164',
    projectId: 'calender-booking-app-123',
    storageBucket: 'calender-booking-app-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFdvlHGHU7sr5EOtAOfsfQHRISRJPBBVQ',
    appId: '1:444197624164:ios:1313f49940e831bfe98271',
    messagingSenderId: '444197624164',
    projectId: 'calender-booking-app-123',
    storageBucket: 'calender-booking-app-123.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFdvlHGHU7sr5EOtAOfsfQHRISRJPBBVQ',
    appId: '1:444197624164:ios:e131538764c0ff33e98271',
    messagingSenderId: '444197624164',
    projectId: 'calender-booking-app-123',
    storageBucket: 'calender-booking-app-123.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
